ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
country=BR

# Rede do carro — configurar antes de gravar o SD card
# network={
#     ssid="NomeDaRedeWiFi"
#     psk="SenhaDoWifi"
# }
